"""auth tokens alerts issues

Revision ID: dbf18f592b02
Revises: 
Create Date: 2026-09-20 05:46:03.687692
"""

from alembic import op
import sqlalchemy as sa


revision = 'dbf18f592b02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_source'), ['source'], unique=False)

    op.create_table('issue_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('station', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_reports_station'), ['station'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_reports_status'), ['status'], unique=False)

    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('assigned_station', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_invited_by_users', 'users', ['invited_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_invited_by_users', type_='foreignkey')
        batch_op.drop_column('invited_by')
        batch_op.drop_column('assigned_station')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_tokens_purpose'))

    op.drop_table('user_tokens')
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_reports_status'))
        batch_op.drop_index(batch_op.f('ix_issue_reports_station'))
        batch_op.drop_index(batch_op.f('ix_issue_reports_reporter_id'))

    op.drop_table('issue_reports')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_source'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_active'))
        batch_op.drop_index(batch_op.f('ix_alerts_entity'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
